# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(236, 277)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setMinimumSize(QtCore.QSize(0, 0))
        self.title.setMaximumSize(QtCore.QSize(16777215, 20))
        self.title.setScaledContents(False)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.SantrollButton = QtWidgets.QPushButton(self.centralwidget)
        self.SantrollButton.setMinimumSize(QtCore.QSize(0, 40))
        self.SantrollButton.setObjectName("SantrollButton")
        self.verticalLayout.addWidget(self.SantrollButton)
        self.CSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.CSVButton.setMinimumSize(QtCore.QSize(0, 40))
        self.CSVButton.setObjectName("CSVButton")
        self.verticalLayout.addWidget(self.CSVButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "画图软件"))
        self.SantrollButton.setText(_translate("MainWindow", "Santroll"))
        self.CSVButton.setText(_translate("MainWindow", "CSV"))
